version: "3.9"

services:
  web:
    build: .
    container_name: auth
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn auth.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./src:/app
    ports:
      - "8082:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: auth_postgressql
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: paytoleg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paytoleg

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: auth_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: auth_redis
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: auth_celery
    command: celery -A auth worker -l info
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
