# Generated by Django 5.2 on 2025-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=20),
        ),
    ]
